### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by mbbasoglu** [hmatejx/xrapid_search#1]
Getting trade history from Bitstamp...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "xrapid_search.py", line 39, in <module>
    res1 = getBitstamp(time=time)
  File "C:\Users\musli\Desktop\xrapid_search-master\exchanges.py", line 45, in getBitstamp
    qtime = bitstamp.client.TransRange.DAY if time == 24 else bitstamp.client.TransRange.HOUR
AttributeError: type object 'TransRange' has no attribute 'DAY'

**Comment by hmatejx** [comment]
This happens if you don't use the [modified bitstamp client](https://github.com/hmatejx/bitstamp-python-client). You should use my version of bitstamp-python-client, it's clearly written in the README.

I've opened a pull request to @kmadac https://github.com/kmadac/bitstamp-python-client/pull/46 to merge my modification into his official repo, but it is not merged yet.
